AllCops:
  Exclude:
    - 'test/encoding_test/*.rb'
    - 'devel/levitate.rb'
    - 'devel/levitate_config.rb'
    - 'vendor/**/*'

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Needed for `unfixable` in tests
Lint/HandleExceptions:
  Exclude:
    - 'test/**/*'
# Allow test classes to have any length
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Allow use of eval in tests (that is sort of the point!)
Security/Eval:
  Exclude:
    - 'test/**/*'

# Allow multi-line blocks of all sorts
Style/BlockDelimiters:
  Enabled: false

# Allow def A.foo in tests
Style/ClassMethods:
  Exclude:
    - 'test/**/*'

Style/DotPosition:
  EnforcedStyle: trailing

# Require empty lines between defs except for one-liners
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Allow both lambda syntaxes in tests
Style/Lambda:
  Exclude:
    - 'test/**/*'
# Allow Proc.new in tests
Style/Proc:
  Exclude:
    - 'test/**/*'

# Allow foo.bar rescue nil in tests
Style/RescueModifier:
  Exclude:
    - 'test/**/*'

# Allow multiple expressions per line
Style/Semicolon:
  AllowAsExpressionSeparator: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Allow non-interpolated strings with double quotes
Style/StringLiterals:
  Enabled: false

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# This test requires its constant to be mutable
Style/MutableConstant:
  Exclude:
    - 'test/full/replace_eval_test.rb'

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Support use of and and or for control flow.
Style/AndOr:
  EnforcedStyle: conditionals

# RuboCop has no setting to accept how vim aligns parameters.
Style/AlignParameters:
  Enabled: false

# Allow semantic choice of trailing comma
Style/TrailingCommaInLiteral:
  Enabled: false

# LiveAST sometimes needs to rescue all exceptions
Lint/RescueException:
  Enabled: false

# Use {} for %-literals
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'

inherit_from: .rubocop_todo.yml
