AllCops:
  Exclude:
    - 'test/encoding_test/*.rb'
    - 'devel/levitate.rb'

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Allow multi-line blocks of all sorts
Style/Blocks:
  Enabled: false

# Require lines to fit in pull requests.
Style/LineLength:
  Max: 92

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Allow non-interpolated strings with double quotes
Style/StringLiterals:
  Enabled: false

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Allow semantic choice of trailing comma
Style/TrailingComma:
  Enabled: false

# The following overrides are needed for the tests.
# Allow multiple expressions per line
Style/Semicolon:
  AllowAsExpressionSeparator: true

# Allow Proc.new
Style/Proc:
  Enabled: false

# Allow foo.bar rescue nil
Style/RescueModifier:
  Enabled: false

# Allow both lambda syntaxes
Style/Lambda:
  Enabled: false

# Allow def A.foo
Style/ClassMethods:
  Enabled: false

inherit_from: .rubocop_todo.yml
