AllCops:
  Exclude:
    - 'test/encoding_test/*.rb'
    - 'devel/levitate.rb'

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Require lines to fit in pull requests.
Style/LineLength:
  Max: 92

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Allow non-interpolated strings with double quotes
Style/StringLiterals:
  Enabled: false

# Allow multi-line blocks of all sorts
Style/Blocks:
  Enabled: false

# Allow semantic choice of trailing comma
Style/TrailingComma:
  Enabled: false

# Allow multiple expressions per line. The tests need this.
Style/Semicolon:
  AllowAsExpressionSeparator: true

inherit_from: .rubocop_todo.yml
