sudo: false
dist: trusty
cache: bundler
language: ruby

before_install:
  - gem update --system

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
